### ISSUE TITLE
Make subrpc as a standard crate

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#1071]
Now there are two version `subrpc`. The original one made by @tenheadedlion is located [here](https://github.com/Phala-Network/index-contract/tree/main/index/src/subrpc). The revised version by me is located [here](https://github.com/Phala-Network/phat-offchain-rollup/tree/main/phat/crates/subrpc) with some new added features.

Considering subrpc is toward production ready level (tested with our offchain rollup demo and workshop), I think it's good to move the second version to the official pink series library. Ideally the developers can use `pink-subprc` from [crates.io].

**Comment by kvinwang** [comment]
Done in https://github.com/Phala-Network/phala-blockchain/pull/1077
