### ISSUE TITLE
pRuntime v0.2.5 fails to restart with kernel 5.13.0

### ISSUE THREAD

**Issue by ngrewe** [Phala-Network/phala-blockchain#1079]
With the new pRuntime version v0.2.5 we're observing some weird behaviour related to ~~re~~starting the container on Ubuntu 20.04 machines with the HWE kernel (5.13.0) installed. ~~It runs fine when starting it initially, but once you've started it once, subsequent restarts~~ The container terminates with this error message:

```
Starting pRuntime with extra opts '--cores=6'
PRuntime will running in hardware mode
pRuntime starting... It may take up to 2 minutes.
Waiting for device. Sleep 6s
aesm_service: warning: Turn to daemon. Use "--no-daemon" option to execute in foreground.
[get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-218/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
thread 'main' panicked at '[-] Init Enclave Failed SGX_ERROR_NO_DEVICE!', src/main.rs:637:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/panicking.rs:106:14
   2: app::main::{{closure}}
   3: tokio::park::thread::CachedParkThread::block_on
   4: tokio::runtime::thread_pool::ThreadPool::block_on
   5: tokio::runtime::Runtime::block_on
   6: rocket::async_main
   7: app::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`SGX_ERROR_NO_DEVICE` seems inacurate in as far as the `/dev/sgx_*` devices are still present on the host. Rebooting the machine will fix this issue and allow the pRuntime to start again. Restarts work normally on the same machine with the older version `22051201`, and also with `v0.2.5` on Ubuntu 20.04 machines that do not have the HWE kernel installed (5.8.0) and hence use Intel's out-of-tree SGX driver (v1.41).

**Comment by ngrewe** [comment]
Sorry, I must have imagined restart part… even after a fresh boot, it won't start properly.

**Comment by jasl** [comment]
Sorry for late response, can you show `ls /dev | grep sgx`

**Comment by ngrewe** [comment]
The cluster has since gone into shutdown for some maintenace while compute functions are offline on Khala. I've observed the issue on machines with different processors, and my recollection is that the device layout was contingent on the processor:

* Core i5-9600KF: `/dev/sgx_provision`, `/dev/sgx_enclave`
* Xeon E-2388G: `/dev/sgx_provision`, `/dev/sgx_enclave`, `/dev/sgx_vepc`

I also vaguely recall that we never have the sgx_vepc device with the 5.8.0 kernel and the out-of-tree driver? Not entirely sure about that, though.

**Comment by jasl** [comment]
> The cluster has since gone into shutdown for some maintenace while compute functions are offline on Khala. I've observed the issue on machines with different processors, and my recollection is that the device layout was contingent on the processor:
> 
> * Core i5-9600KF: `/dev/sgx_provision`, `/dev/sgx_enclave`
> * Xeon E-2388G: `/dev/sgx_provision`, `/dev/sgx_enclave`, `/dev/sgx_vepc`
> 
> I also vaguely recall that we never have the sgx_vepc device with the 5.8.0 kernel and the out-of-tree driver? Not entirely sure about that, though.

The out-of-tree driver doesn't have `sgx_vepc`, I suggest you try latest Ubuntu 20.04 or 22.04 with kernel bundled driver (in-tree drvier)

**Comment by ngrewe** [comment]
> I suggest you try latest Ubuntu 20.04 or 22.04 with kernel bundled driver (in-tree drvier)

I think I might have phrased that badly: We do _not_ have a problem with the out-of-tree driver, the problem we are experiencing is only in combination of pRuntime v0.2.5 and the 5.13.0 kernel shipped with Ubuntu 20.04 as an HWE stack. 
Kernel 5.8.0 (out-of-tree driver) with pRuntime v0.2.5 is fine and kernel 5.13.0 (in-tree-driver) with pRuntime 22051201 is also fine.

I'll see whether we can get kernel 5.15.0 onto the 20.04 machines when we go back online and see whether that makes a difference.

**Comment by krhougs** [comment]
The version of the running SDK uses the old way of SGX device naming.

Consider use these device mapping when starting the container: 
`--device /dev/sgx_enclave:/dev/sgx/enclave --device /dev/sgx_provision:/dev/sgx/provision --device /dev/sgx_provision --device /dev/enclave`

**Comment by ngrewe** [comment]
In the meantime, Ubuntu 20.04 is shipping a HWE kernel that works fine.
