### ISSUE TITLE
Nightly prebuilt binaries don't work with Ubuntu 22.04

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#1142]
Especially pruntime cannot execute because Ubuntu 22.04 is shipped with libssl-3 instead of 1.1. It shows the following error:

```
./nightly-2023-01-30/pruntime: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Potential solutions:

1. Suggest `devphase` to run prebuilt binaries from a Ubuntu 20.04 docker container
2. Ship all the dylibs together with the prebuilt binaries ([example](https://stackoverflow.com/a/73475300/2206993))
3. Statically link dependencies in pruntime

**Comment by h4x3rotab** [comment]
Script for ~~solution~~ walkaround 2

```bash
# Download, compile, and install openssl-1.1 to $HOME/.local
wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
tar -zxvf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o
./config --prefix=$HOME/.local --openssldir=$HOME/.local
make
make test
make install

# Then set the env var before running pruntime
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/.local/lib"
```

**Comment by l00k** [comment]
https://github.com/Phala-Network/phala-blockchain/pull/1143
According to this, next releases should not cause issues.
