### ISSUE TITLE
error[E0152]: duplicate lang item in crate `ink_env` for the S3 crate when i try to compile it.

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/phala-blockchain#1180]
Hi, PhalaTeam !

I'm trying to use the S3 crate with ink4 but i meet perpetually this error `error[E0152]: duplicate lang item in crate "ink_env\" (which `ink` depends on): `panic_impl`.` : ` below is my most simplified version.

 ```
Compiling pink-s3 v0.4.0
error[E0152]: duplicate lang item in crate "ink_env" (which "ink" depends on): "panic_impl".
  |
  = note: the lang item is first defined in crate "std" (which "pink_s3" depends on)
  = note: first definition in "std" loaded from /root/contracts/target/ink/wasm32-unknown-unknown/release/deps/libstd-ed63f69e89d218fa.rmeta
  = note: second definition in "ink_env" loaded from /root/contracts/target/ink/wasm32-unknown-unknown/release/deps/libink_env-3f65290641ea9f9f.rmeta

For more information about this error, try "rustc --explain E0152".
error: could not compile "pink-s3" due to previous error
warning: build failed, waiting for other jobs to finish...
```

```
rustc -V
rustc 1.67.0 (fc594f156 2023-01-24)
cargo contract -V
cargo-contract-contract 2.0.1-unknown-x86_64-unknown-linux-gnu
```

Cargo.toml : 

```
[package]
name = "phat2meet"
version = "0.1.0"
authors = ["PhalaTeamFR-https://linktr.ee/phalafr"]
edition = "2021"

[dependencies]
pink-s3 = { version = "0.4.0", default-features = false }

[dev-dependencies]

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "pink-s3/std",
]
ink-as-dependency = []
```

lib.rs

```
#![cfg_attr(not(feature = "std"), no_std)]

use pink_s3 as s3;

let endpoint = "s3.ap-southeast-1.amazonaws.com";
let region = "ap-southeast-1";
let access_key = "<Put your S3 access key here>";
let secret_key = "<Put your S3 access secret key here>";

let s3 = s3::S3::new(endpoint, region, access_key, secret_key)
    .unwrap()
    .virtual_host_mode(); // virtual host mode is required for newly created AWS S3 buckets.

let bucket = "my-wallet";
let object_key = "path/to/foo";
let value = b"bar";

s3.put(bucket, object_key, value).unwrap();

let head = s3.head(bucket, object_key).unwrap();
assert_eq!(head.content_length, value.len() as u64);

let v = s3.get(bucket, object_key).unwrap();
assert_eq!(v, value);

s3.delete(bucket, object_key).unwrap();
```

**Comment by kvinwang** [comment]
Shoud be fixed in https://github.com/Phala-Network/phala-blockchain/pull/1182.

**Comment by tionebDotsamapha** [comment]
thank you very much for your reactivity @kvinwang ! 
I tried your example and I can compile it !

but i couldn't use it in the testnet : https://phat-cb.phala.network/contracts/add
endpoint ->  wss://phat-beta-node.phala.network/khala/ws

```
Error
Your contract metadata version is too low, Please upgrade your cargo-contract with `cargo install cargo-contract --force`.
```

exemple.json
`"source": {
    "hash": "0x67695d4833b2844b2fef08411dc1a39bb3a68fc953e456c36679d0d63dca2f25",
    "language": "ink! 4.0.1",
    "compiler": "rustc 1.67.0",
    "build_info": {
      "build_mode": "Debug",
      "cargo_contract_version": "2.0.1",
      "rust_toolchain": "stable-x86_64-unknown-linux-gnu",
      "wasm_opt_settings": {
        "keep_debug_symbols": false,
        "optimization_passes": "Z"
      }
    }
  },
  "contract": {
    "name": "example",
    "version": "0.1.0",
    "authors": [
      "<author>"
    ]
  },
  "spec": {
    "constructors": [
      {
        "args": [],
        "docs": [],
        "label": "default",
        "payable": false,
        "returnType": {
          "displayName": [
            "ink_primitives",
            "ConstructorResult"
          ],
          "type": 0
        },
        "selector": "0xed4b9d1b"
      }
    ],
    "docs": [],
    "events": [],
    "lang_error": {
      "displayName": [
        "ink",
        "LangError"
      ],
      "type": 2
    },
    "messages": [
      {
        "args": [],
        "docs": [],
        "label": "it_works",
        "mutates": false,
        "payable": false,
        "returnType": {
          "displayName": [
            "ink",
            "MessageResult"
          ],
          "type": 0
        },
        "selector": "0x4973c530"
      }
    ]
  },
  "storage": {
    "root": {
      "layout": {
        "struct": {
          "fields": [],
          "name": "Example"
        }
      },
      "root_key": "0x00000000"
    }
  },
  "types": [
    {
      "id": 0,
      "type": {
        "def": {
          "variant": {
            "variants": [
              {
                "fields": [
                  {
                    "type": 1
                  }
                ],
                "index": 0,
                "name": "Ok"
              },
              {
                "fields": [
                  {
                    "type": 2
                  }
                ],
                "index": 1,
                "name": "Err"
              }
            ]
          }
        },
        "params": [
          {
            "name": "T",
            "type": 1
          },
          {
            "name": "E",
            "type": 2
          }
        ],
        "path": [
          "Result"
        ]
      }
    },
    {
      "id": 1,
      "type": {
        "def": {
          "tuple": []
        }
      }
    },
    {
      "id": 2,
      "type": {
        "def": {
          "variant": {
            "variants": [
              {
                "index": 1,
                "name": "CouldNotReadInput"
              }
            ]
          }
        },
        "path": [
          "ink_primitives",
          "LangError"
        ]
      }
    }
  ],
  "version": "4"
}`

**Comment by kvinwang** [comment]
The testnet endpoint and Phat UI don't support ink-4 yet.

**Comment by tionebDotsamapha** [comment]
Solved, I close the issue.
Thank you another time.

**Comment by tionebDotsamapha** [comment]
@kvinwang is there another place where we can test ink4?

**Comment by kvinwang** [comment]
> @kvinwang is there another place where we can test ink4?

We can easily set up a local test net with devphase like the repo [shelvenzhou/phat-lego-oracle](https://github.com/shelvenzhou/phat-lego-oracle) does.

Looks like there is still a problem with compiling using devphase. @shelvenzhou might give more detail there.
