### ISSUE TITLE
The latest code compilation error in the `master` branch (commit:`99e7a2c8`)

### ISSUE THREAD

**Issue by 0xbillw** [Phala-Network/phala-blockchain#1581]
I pull down the latest code (`master` branch, commit:`99e7a2c8`, workspace is clean) and use `./scripts/run/build.sh` to build, but encountered a compilation error:
![image](https://github.com/Phala-Network/phala-blockchain/assets/1937193/5b428119-bfbb-405c-91e4-46e254b27d4d)

**Comment by 0xbillw** [comment]
It's compiled ok since I pulled the latest commit `ff9d2f60b`

**Comment by h4x3rotab** [comment]
Happy to know you finally went through it. Please let me know if there's anything I can help.
