### ISSUE TITLE
Pass environment variable in the enclave

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#181]
#178 introduced `env_logger` to phost and pruntime. However now it's set to print the full logs because the environment variables are not passed from the outside to the enclave properly. Some early investigation showed `env::vars()` returned an empty array.

![image](https://user-images.githubusercontent.com/1343470/113326567-6a96d700-934c-11eb-86cb-0d43772461b7.png)

This problem is specific to teaclave-sgx-sdk. Their sample env_logger code works and thus the environment variables are passed correctly. We should check how the difference was introduced

**Comment by KiChjang** [comment]
I think this one can be closed since it's been solved by #178?

**Comment by h4x3rotab** [comment]
Yes, thanks!
