### ISSUE TITLE
Mining stakepool

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#218]
Crowdloan-style staking for miners. It should:

- apply a delay for all the operations (contribute, withdraw funds, start / stop mining)
- pool funds and stake for a single miner
- distribute reward an apply slash proportionally to the contributors

Depends on #259

**Comment by tolak** [comment]
- apply a delay for all the operations (contribute, withdraw funds, start / stop mining)
@h4x3rotab Why we should delay here? And what the delay exactly mean?

**Comment by h4x3rotab** [comment]
Will be fixed by #271, #277

**Comment by h4x3rotab** [comment]
After a long journey, we have finally reached the point very close to a release. Let's close this issue, and track the bugs by individual tickets.
