### ISSUE TITLE
sgx_mode=sw make which take the error: failed to get `sgx_types` 

### ISSUE THREAD

**Issue by jarifee** [Phala-Network/phala-blockchain#220]
Updating git submodule `https://github.com/WebAssembly/testsuite`
error: failed to get `sgx_types` as a dependency of package `app v0.0.1 (/home/wsf/phala-blockchain/pruntime/app)`

Caused by:
  failed to load source for dependency `sgx_types`

Caused by:
  Unable to update https://github.com/apache/teaclave-sgx-sdk.git?rev=v1.1.2#8f065be7

Caused by:
  failed to update submodule `samplecode/wasmi/test_input`

Caused by:
  failed to fetch submodule `samplecode/wasmi/test_input` from https://github.com/WebAssembly/testsuite

Caused by:
  SSL error: received early EOF; class=Ssl (16); code=Eof (-20)
Makefile:162: recipe for target 'bin/app' failed
make: *** [bin/app] Error 101

**Comment by h4x3rotab** [comment]
SSL error is usually related to bad proxy setting. Could you check your proxy? Maybe you want to check `env` outputs

**Comment by jarifee** [comment]
> SSL error is usually related to bad proxy setting. Could you check your proxy? Maybe you want to check `env` outputs

thx, I run more time and pass.
