### ISSUE TITLE
Robust pRuntime mq egress syncing

### ISSUE THREAD

**Issue by kvinwang** [Phala-Network/phala-blockchain#232]
Mentioned by @h4x3rotab in #224:

> This could be problematic. The submitted transaction it supposed to change `mq_ingress_seq`. But in reality, the tx can have delay, and can be rolled back in some rare case.
> 
> Let's be careful. The old implementation also has similar issue. We don't need to solve this problem in this PR, but we should design a correct mechanism to handle it anyway.
> 
> Life of a tx:
> 
> 1. When you submit a tx, it goes to a "memory pool" first (when `.submit()` returns). Only the most basic error like empty account can be detected.
> 2. Then the tx from the memory pool will be selected and packed into a block, sequentialize the transactions.
>     - After the block is made, node will execute the tx, and check if it succeed or not
>     - Be careful: multiple nodes can propose different blocks simultaneously, resulting some "forks"
> 3. A consensus algorithm runs on the new block candidates, and select one to be "finalize" (usually in 2 blocks)
>     - Only one block can win the election, and finalized blocks will never be rolled-back
>     - In other words, some unfinalized block candidates can also lose the election
> 
> Suppose we submit a message, it gets immediately included in the mempool. Although there's no guarantee the tx will be finalized, but it's always good to assume so, and we should avoid submitting the same message to the node.
> 
> .. except some edge cases:
> 
> - The mempool may drop the tx when there's block congestion.
> - The tx is included in an unfinalized block first. And at the same time, we can see "mq_ingress_seq" updated. But then a competing block wins the finalization election, resulting the unfinalized block "gets reverted" (in the view of the local node, also called "chain reorganization"). In this case, the client can even see "mq_ingress_seq" decreasing.
> 
> Usually it's safe to assume nodes will try their best to get the mempool txs finalized. In the case of a reorg, the node should pick up the missing tx, and try to include it in the next block, unless there's a serious block congestion.
> 
> Btw, each transaction has a expiration time. When a congestion happens, the block can only live in the mempool for some time (usually 3-15 mins). A too old tx will be dropped.
> 
>

**Comment by h4x3rotab** [comment]
Two dimensions:

1. On substrate end, we can reject any redundant message being added to the mempool, identified by `(sender, seq)` tuple
2. On the relayer end, we can track the submitted seq locally (or by adding a RPC to substrate to look up the latest seq in the mempool), to avoid redundant submission

**Comment by h4x3rotab** [comment]
Depends on https://github.com/paritytech/substrate/issues/9363

**Comment by h4x3rotab** [comment]
After the testnet simulation, we found it very annoying. It burns a lot of transaction fee.

After syncing every message successfully, `pherry` will still try to send the message again and again, until the message is confirmed on the blockchain. On parachain the delay is usually 48 sec, and `pherry` retries every 6 sec, meaning it pushes ~8 redundant transactions for each new message.
