### ISSUE TITLE
rpc请求author_rotateKeys返回Method not found

### ISSUE THREAD

**Issue by sidealice** [Phala-Network/phala-blockchain#243]
验证者需要有keys，我输入以下命令
 curl -sH "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://node:9933
返回
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
是否需要对节点额外进行配置启动命令，比如在启动的时候需要设置--key='newkey'的参数？

**Comment by sidealice** [comment]
rpc.rs

    /// Generate new session keys and returns the corresponding public keys.
    pub async fn rotate_keys(&self) -> Result<Bytes, Error> {
        self.rpc.rotate_keys().await
    }

**Comment by h4x3rotab** [comment]
https://github.com/paritytech/polkadot/issues/1082

**Comment by sidealice** [comment]
谢谢。我试一下。

**Comment by sidealice** [comment]
我刚刚试了最新的dev节点，有返回结果了。 谢谢！
