### ISSUE TITLE
Native build failed!

### ISSUE THREAD

**Issue by YunL0ngLee** [Phala-Network/phala-blockchain#244]
Local Env:
![image](https://user-images.githubusercontent.com/30599323/124086090-4ea5ed00-da83-11eb-9d8e-f9d1593af5b8.png)

Code Version:
![image](https://user-images.githubusercontent.com/30599323/124086292-7eed8b80-da83-11eb-8256-85a13f9999c3.png)

Error Message:
   Compiling sc-chain-spec v3.0.0 (/root/phala-blockchain/substrate/client/chain-spec)
   Compiling sc-finality-grandpa-rpc v0.9.0 (/root/phala-blockchain/substrate/client/finality-grandpa/rpc)
   Compiling pallet-staking v3.0.0 (/root/phala-blockchain/substrate/frame/staking)
   Compiling pallet-authority-discovery v3.0.0 (/root/phala-blockchain/substrate/frame/authority-discovery)
   Compiling pallet-babe v3.0.0 (/root/phala-blockchain/substrate/frame/babe)
   Compiling pallet-grandpa v3.1.0 (/root/phala-blockchain/substrate/frame/grandpa)
   Compiling sc-sync-state-rpc v0.9.0 (/root/phala-blockchain/substrate/client/sync-state-rpc)
   Compiling node-rpc v2.0.0 (/root/phala-blockchain/standalone/rpc)
   Compiling rpc-ext v0.1.0 (/root/phala-blockchain/standalone/rpc-ext)
   Compiling substrate-subxt v0.15.0 (/root/phala-blockchain/subxt)
error: failed to run custom build command for `phala-node-runtime v2.0.0 (/root/phala-blockchain/standalone/runtime)`

Caused by:
  process didn't exit successfully: `/root/phala-blockchain/target/release/build/phala-node-runtime-2605502fe8928511/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/root/.rustup/toolchains/nightly-2021-05-11-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/root/phala-blockchain/target/release/wbuild/phala-node-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.54.0-nightly (79e50bf77 2021-05-10)

  --- stderr
     Compiling proc-macro2 v1.0.27
     Compiling unicode-xid v0.2.2
     Compiling syn v1.0.73
     Compiling serde_derive v1.0.126
     Compiling serde v1.0.126
     Compiling autocfg v1.0.1
     Compiling arrayvec v0.7.1
     Compiling byteorder v1.4.3
     Compiling byte-slice-cast v1.0.0
     Compiling crunchy v0.2.2
     Compiling log v0.4.14
     Compiling memchr v2.4.0
     Compiling static_assertions v1.1.0
     Compiling cfg-if v1.0.0
     Compiling hex v0.4.3
     Compiling pin-project-lite v0.2.6
     Compiling regex-syntax v0.6.25
     Compiling sp-std v3.0.0 (/root/phala-blockchain/substrate/primitives/std)
     Compiling ahash v0.4.7
     Compiling lazy_static v1.4.0
     Compiling ref-cast v1.0.6
     Compiling parity-util-mem v0.9.0
     Compiling hash-db v0.15.2
     Compiling tracing-core v0.1.18
     Compiling either v1.6.1
     Compiling paste v1.0.5
     Compiling radium v0.6.2
     Compiling tap v1.0.1
     Compiling funty v1.1.0
     Compiling wyz v0.2.0
     Compiling bitflags v1.2.1
     Compiling smallvec v1.6.1
     Compiling arrayvec v0.4.12
     Compiling libc v0.2.97
     Compiling nodrop v0.1.14
     Compiling constant_time_eq v0.1.5
     Compiling ryu v1.0.5
     Compiling typenum v1.13.0
     Compiling rand_core v0.5.1
     Compiling futures-core v0.3.15
     Compiling ucd-trie v0.1.3
     Compiling futures-task v0.3.15
     Compiling subtle v2.4.0
     Compiling byte-tools v0.3.1
     Compiling zstd-safe v3.0.1+zstd.1.4.9
     Compiling serde_json v1.0.64
     Compiling camino v1.0.4
     Compiling arrayref v0.3.6
     Compiling ppv-lite86 v0.2.10
     Compiling untrusted v0.7.1
     Compiling futures-channel v0.3.15
     Compiling futures-sink v0.3.15
     Compiling safe-mix v1.0.1
     Compiling semver-parser v0.7.0
     Compiling opaque-debug v0.2.3
     Compiling itoa v0.4.7
     Compiling keccak v0.1.0
     Compiling fake-simd v0.1.2
     Compiling pin-utils v0.1.0
     Compiling base64 v0.11.0
     Compiling futures-io v0.3.15
     Compiling arrayvec v0.5.2
     Compiling same-file v1.0.6
     Compiling remove_dir_all v0.5.3
     Compiling rustc-demangle v0.1.20
     Compiling ansi_term v0.12.1
     Compiling num-traits v0.2.14
     Compiling num-integer v0.1.44
     Compiling futures-util v0.3.15
     Compiling fixed-hash v0.7.0
     Compiling hashbrown v0.9.1
     Compiling trie-root v0.16.0
     Compiling tracing v0.1.26
     Compiling itertools v0.8.2
     Compiling pest v2.1.3
     Compiling block-padding v0.1.5
     Compiling semver v0.6.0
     Compiling rand_chacha v0.2.2
     Compiling parity-wasm v0.32.0
     Compiling walkdir v2.3.2
     Compiling build-helper v0.1.1
     Compiling rand v0.7.3
     Compiling semver-parser v0.10.2
     Compiling quote v1.0.9
     Compiling uint v0.9.0
     Compiling hash256-std-hasher v0.15.2
     Compiling trie-db v0.22.5
     Compiling bitvec v0.20.4
     Compiling aho-corasick v0.7.18
     Compiling blake2-rfc v0.2.18
     Compiling wasm-gc-api v0.1.11
     Compiling jobserver v0.1.22
     Compiling getrandom v0.2.3
     Compiling atty v0.2.14
     Compiling generic-array v0.12.4
     Compiling integer-sqrt v0.1.5
     Compiling regex v1.5.4
     Compiling cc v1.0.68
     Compiling rand_core v0.6.3
     Compiling digest v0.8.1
     Compiling block-buffer v0.7.3
     Compiling chrono v0.4.19
     Compiling futures v0.3.15
     Compiling Inflector v0.11.4
     Compiling zstd-sys v1.4.20+zstd.1.4.9
     Compiling ring v0.16.20-1 (/root/phala-blockchain/ring)
     Compiling rand_chacha v0.3.1
     Compiling libsecp256k1 v0.3.5
     Compiling sha2 v0.8.2
     Compiling synstructure v0.12.4
     Compiling rand v0.8.4
  error: failed to run custom build command for `ring v0.16.20-1 (/root/phala-blockchain/ring)`

  Caused by:
    process didn't exit successfully: `/root/phala-blockchain/target/release/wbuild/phala-node-runtime/target/release/build/ring-8cf03694b46a8d25/build-script-build` (exit status: 101)
    --- stdout
    OPT_LEVEL = Some("3")
    TARGET = Some("wasm32-unknown-unknown")
    HOST = Some("x86_64-unknown-linux-gnu")
    CC_wasm32-unknown-unknown = None
    CC_wasm32_unknown_unknown = None
    TARGET_CC = None
    CC = None
    CFLAGS_wasm32-unknown-unknown = None
    CFLAGS_wasm32_unknown_unknown = None
    TARGET_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("false")

    --- stderr
    running "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-nostdlibinc" "-DNDEBUG" "-DGFp_NOSTDLIBINC=1" "-c" "-o/root/phala-blockchain/target/release/wbuild/phala-node-runtime/target/wasm32-unknown-unknown/release/build/ring-2e3d7d0e583bcd49/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
    thread 'main' panicked at 'failed to execute ["clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-nostdlibinc" "-DNDEBUG" "-DGFp_NOSTDLIBINC=1" "-c" "-o/root/phala-blockchain/target/release/wbuild/phala-node-runtime/target/wasm32-unknown-unknown/release/build/ring-2e3d7d0e583bcd49/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"]: No such file or directory (os error 2)', /root/phala-blockchain/ring/build.rs:715:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by h4x3rotab** [comment]
You need to install the latest llvm (llvm-10 or higher)

**Comment by YunL0ngLee** [comment]
> You need to install the latest llvm (llvm-10 or higher)
![image](https://user-images.githubusercontent.com/30599323/124096718-6da97c80-da8d-11eb-818f-8a45267ce1e9.png)

Like this?

**Comment by h4x3rotab** [comment]
What does `llvm --version` show? A possibility is that you may have installed multiple versions, and it found an older version.

**Comment by YunL0ngLee** [comment]
> What does `llvm --version` show? A possibility is that you may have installed multiple versions, and it found an older version.

![image](https://user-images.githubusercontent.com/30599323/124116632-c125c580-daa1-11eb-8aa1-315b0ff74c8c.png)

**Comment by h4x3rotab** [comment]
Probably you need to figure out how to install LLVM properly. You may need to link it to `llvm-ar` and `clang` rather than the versioned name. You can also check out CC crate's environment variable to learn how to specify a special version of LLVM.

Sorry, we don't have more bandwidth to help you triage the problem in the recent weeks.

**Comment by YunL0ngLee** [comment]
> Probably you need to figure out how to install LLVM properly. You may need to link it to `llvm-ar` and `clang` rather than the versioned name. You can also check out CC crate's environment variable to learn how to specify a special version of LLVM.
> 
> Sorry, we don't have more bandwidth to help you triage the problem in the recent weeks.

Ok,i will try it.Thanks a lot

**Comment by h4x3rotab** [comment]
Does it work now?
