### ISSUE TITLE
Critical database error

### ISSUE THREAD

**Issue by wowvwow** [Phala-Network/phala-blockchain#253]
====================

Version: 3.0.0-da3469f-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/panicking.rs:493:5
   5: std::panicking::begin_panic_fmt
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/panicking.rs:435:5
   6: <sc_client_db::parity_db::DbAdapter as sp_database::Database<H>>::commit
   7: sc_client_db::Backend<Block>::try_commit_operation
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
   9: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::AuxStore>::insert_aux
  10: sc_consensus_slots::aux_schema::check_equivocation
  11: sc_consensus_babe::BabeVerifier<Block,Client,SelectChain,CAW>::check_and_report_equivocation
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  17: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  20: std::thread::local::LocalKey<T>::with
  21: futures_executor::local_pool::block_on
  22: tokio::runtime::task::core::Core<T,S>::poll
  23: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::context::enter
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d9c2c92b834c430f102ea96f65119e37320776e/library/std/src/sys/unix/thread.rs:71:17
  29: start_thread
  30: clone

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Background(Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))', /root/phala-blockchain/substrate/client/db/src/parity_db.rs:30

**Comment by h4x3rotab** [comment]
Sometimes this could happen if you didn't close the node elegantly. In that case you have to resync the full node from scratch.
