### ISSUE TITLE
Gatekeeper as a source of on-chain VRF

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#263]
As a temporary solution to replace Babe in parachain

**Comment by shelvenzhou** [comment]
Gatekeepers regularly emit RandomNumberEvent on-chain. Also, this event serves as an entropy source of the Randomness Collective Flip module we use, since it, as I quote,  "generates low-influence random values based on the block hashes from the previous 81 blocks".
