### ISSUE TITLE
Task score logic is incomplete?

### ISSUE THREAD

**Issue by Xib1uvXi** [Phala-Network/phala-blockchain#264]
Hi, I was confused about current master code for the task score logic.
1. The intial_score of worker info is mutated as phala.WorkerInfo. (https://github.com/Phala-Network/phala-blockchain/blob/aa202de5887c7f957645c976879e269936ad0bcc/pallets/phala/src/registry.rs#L312)
2. The pRuntime reads worker info as phala_types.WorkerInfo in state snapshot and uses its score field when electing TEE workers for computing task. (https://github.com/Phala-Network/phala-blockchain/blob/cd09ce090da50686b38d7f0d16dc5929b4d15e74/standalone/pruntime/enclave/src/system/comp_election.rs#L64)
I wonder where does the conversion from phala.WorkerInfo to phala_types.WorkerInfo happend?

**Comment by h4x3rotab** [comment]
Sorry for the confusion. #257 will remove comp_election completely, and the old WorkerInfo will be retired soon.

We will not post any "virtual computing tasks" to the network in the future, according to our [new tokenomic](https://medium.com/phala-network/reading-phala-network-economic-paper-preview-5f33b7019861). Instead, we will run the "Value Promised" model, and assign different growth / payout rate for Active miners.

**Comment by Xib1uvXi** [comment]
@h4x3rotab  thx
