### ISSUE TITLE
SGX_ERROR_UPDATE_NEEDED

### ISSUE THREAD

**Issue by guodayang007** [Phala-Network/phala-blockchain#284]
✔  SGX instruction set
  ✔  CPU support
  ✔  CPU configuration
  ✔  Enclave attributes
  ✔  Enclave Page Cache
  SGX features
    ✘  SGX2  ✘  EXINFO  ✘  ENCLV  ✘  OVERSUB  ✘  KSS
    Total EPC size: 94.0MiB
✔  Flexible launch control
  ✔  CPU support
  ？ CPU configuration
  ✔  Able to launch production mode enclave
✔  SGX system software
  ✔  SGX kernel device (/dev/sgx/enclave)
  ✔  libsgx_enclave_common
  ✔  AESM service
  ✔  Able to launch enclaves
    ✔  Debug mode
    ✔  Production mode
    ✔  Production mode (Intel whitelisted)

You're all set to start running SGX programs!
Generated machine id:
[60, 212, 107, 112, 145, 43, 158, 204, 71, 60, 57, 88, 193, 218, 45, 104]

CPU Cores:
8

Encoded runtime info:
[1, 0, 0, 0, 60, 212, 107, 112, 145, 43, 158, 204, 71, 60, 57, 88, 193, 218, 45, 104, 2, 173, 178, 243, 192, 209, 17, 12, 106, 156, 182, 78, 76, 200, 249, 199, 64, 177, 207, 236, 133, 147, 49, 166, 6, 22, 90, 22, 89, 17, 205, 190, 118, 8, 8, 0, 0, 0, 1, 0, 0, 0]
Testing RA...
aesm_service[15]: [ADMIN]EPID Provisioning initiated
aesm_service[15]: The Request ID is 3c8a0adcc8454af9b0d53757c9a9f8e3
aesm_service[15]: The Request ID is 478d6a682ba546dd8b953a999dc2a79c
aesm_service[15]: [ADMIN]EPID Provisioning protocol error reported by Backend (9)
aesm_service[15]: [ADMIN]EPID Provisioning failed
thread '<unnamed>' panicked at 'error while doing remote attestation: SGX_ERROR_UPDATE_NEEDED', src/lib.rs:448:132
note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
fatal runtime error: failed to initiate panic, error 5
./start_sgx_detect.sh: line 20:    41 Illegal instruction     (core dumped) ./app

**Comment by guodayang007** [comment]
BIOS It's the latest version 
configure
Board：MAG B460 TORPEDO (MS-7C81)
CPU ：Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz

**Comment by h4x3rotab** [comment]
You can check the microcode version of the BIOS. Sometimes manufacturers release a new BIOS but with old microcode. You need to request a MCU (microcode update).
