### ISSUE TITLE
StakePool cross-pool locking

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#291]
We need to maintain a ledger for each staker for the total stake. One user can participate in multiple pools. So we need to maintain a total ledger of all contributions.

- [x] Implementation: #294 
- [ ] Unit tests: #302

**Comment by tolak** [comment]
Looks like we can not handle the scenario that people lock/unlock in others place(out pallet stakepool) event we maintain a ledger of pools staking

**Comment by tolak** [comment]
A PR alredy created to implement this, see #294
