### ISSUE TITLE
Metadata awareness in pherry

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#369]
Substrate supports on-chain runtime upgrade. When an upgrade happens, the metadata will be updated as well. 

A metadata update causes `pherry` failed to send any future transactions. Transactions are signed and sent out by `pherry` constantly. The signing process involves the metadata version. Whenever it updates, the signature produced with the old version metadata will be invalid.

Solution: watch the metadata update on the blockchain, and recreate a `subxt` instance to force update the metadata.

**Comment by krhougs** [comment]
Is it related to prb, it seems @polkadot/api handles on-chain runtime upgrade automatically.

**Comment by h4x3rotab** [comment]
No. Polkadot.js doesn't handle anything. A refresh of the Web Apps is required to send transactions

**Comment by h4x3rotab** [comment]
Partially fixed by #545
