### ISSUE TITLE
Move ring & webpki to standalone repos, and maybe submit to upstream

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#4]
We forked `ring` and `webpki` and ported them to support WASM and no_std environment in Substrate.

We should move them out of this repo. Ideally we should try to merge the changes to the upstream.

Update: Now it seems the upstream has already added more wasm support. Consider if it's necessary to keep our fork.

**Comment by burdges** [comment]
It'll be tricky to get PRs merged into ring, but we could reach some consensus among users with related concerns.

**Comment by h4x3rotab** [comment]
Fixed by: 0a710114b7e45e14eebf696f42e24cad6c46b680

The upstream already supports C fallback, and thus can be compiled to wasm.
