### ISSUE TITLE
Will Phala network cooperate with crust network to start dual mining?

### ISSUE THREAD

**Issue by regentropfenbinacs** [Phala-Network/phala-blockchain#400]
According to the [article](https://toutiao.io/posts/ra9s3dl/preview).

When will the relevant protocol design be released?

Ping @h4x3rotab @kvinwang @shelvenzhou 

Thanks a lot ^-^

**Comment by h4x3rotab** [comment]
There's not official integration guide now. However since the both projects requires SGX hardware, it's possible to run them together. Need to take extra care about CPU usage.

**Comment by h4x3rotab** [comment]
Closing for now. Feel free to reopen if you still have any questions
