### ISSUE TITLE
ipinfo.io 大陆地区无法访问 导致pherry卡住

### ISSUE THREAD

**Issue by cnwyx** [Phala-Network/phala-blockchain#484]
https://github.com/Phala-Network/phala-blockchain/blob/9676f649f2a5867a032859419aade8d786eaeb7e/standalone/pherry/src/main.rs#L713

ipinfo.io 大陆地区无法访问 导致pherry卡住 直到超时 下一轮继续卡住
电信线路 移动线路 都一样

`[2021-09-17T22:45:36Z WARN  pherry] FailedToSendGeolocation: "Failed to retrieve geolocation: error sending request for url (https://ipinfo.io/ip): error trying to connect: tcp connect error: Connection timed out (os error 110)\n\nCaused by:\n    0: error trying to connect: tcp connect error: Connection timed out (os error 110)\n    1: tcp connect error: Connection timed out (os error 110)\n    2: Connection timed out (os error 110)"`

root@p00:/opt/phala# wget https://ipinfo.io/ip
--2021-09-18 06:47:39--  https://ipinfo.io/ip
Resolving ipinfo.io (ipinfo.io)... 34.117.59.81
Connecting to ipinfo.io (ipinfo.io)|34.117.59.81|:443... failed: Connection timed out.
Retrying.

--2021-09-18 06:47:43--  (try: 2)  https://ipinfo.io/ip
Connecting to ipinfo.io (ipinfo.io)|34.117.59.81|:443... failed: Connection timed out.
Retrying.

--2021-09-18 06:47:48--  (try: 3)  https://ipinfo.io/ip
Connecting to ipinfo.io (ipinfo.io)|34.117.59.81|:443... failed: Connection timed out.
Retrying.

--2021-09-18 06:47:54--  (try: 4)  https://ipinfo.io/ip
Connecting to ipinfo.io (ipinfo.io)|34.117.59.81|:443... ^C

**Comment by h4x3rotab** [comment]
临时解决方法：在 /etc/hosts 里添加 127.0.0.1 ipinfo.io
