### ISSUE TITLE
(Unconfirmed) No reward while staying Mining

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#489]
Examples:

```
worker: 0xc61a36e1dc2ec0af18dd6cbc8f591628d1cce5b7351edeb3bc25288a2260785b
fee account: 43DBxPRGwWTpNvG99w2JJDEMYGcQmpvP9EvvdRKk2jfMJBGA
```

```
worker: 0x3096272db93787abf6b52b60fe8cd79dcf0076544871182b18a6e3be0e53ad35
fee account: 45vgjavfYYzCh34Q8ebsWEUCMcVkYJ3bswXtNWoGe22RrZ6F
```

**Comment by the729** [comment]
Old version of pherry will, by default, check the geolocation of the miner. It will try to get the public IP through https://ipinfo.io/ip, which, however, is block by the Firewall. 
This will block pherry's main loop for a few minutes each time, preventing it from fully sync with the node.

**Comment by h4x3rotab** [comment]
@the729 For this case, an upgrade of the `pherry` docker image should fix it. It was already fixed by #485 (linked issue #484)

Anyway, if it's stuck, the worker shouldn't be able to answer the heartbeat challenge in time, resulting `MiningUnresopnsive`. So I was curious why it shows MiningIdle while no reward is generated.

**Comment by the729** [comment]
I experienced this exact issue 48hrs ago. The miner did answer with a huge delay, but probably not late enough to be considered `MiningUnresopnsive`. 
My miner became `MiningUnresopnsive` once, and recovered quickly. Nevertheless, no coin minted during the process. 

Probably the real issue here is: why not `Unresponsive` yet not minting coins.

**Comment by wscn16** [comment]
worker: 0x8e2c313f7ce82221154b930657d7866ee9561dbecb825fb7f11beafef34c2e77
fee account: 45232V185m3h2P2ZSpt7MdGLNv49odjdvUCiJpKemVLr3nsV

**Comment by zengxiang1** [comment]
worker: 0x9499acd7485a695f08f3cb1eac68b552caf1f156f99ff70b0ce80e8d593b3d78
fee account: 3ztZjsDtb8esfGcQhRR37ndbbxkaFCWgXohUYbDQobSEVfvA

**Comment by zengxiang1** [comment]
upgrade of the pherry docker image can fix it

**Comment by zengxiang1** [comment]
> upgrade of the pherry docker image can fix it

`sudo phala stop `
`sudo docker pull phalanetwork/phala-pherry:latest`
`sudo phala start`

**Comment by wscn16** [comment]
> > pherry docker 镜像的升级可以修复它
> 
> `sudo phala stop `
> `sudo docker pull phalanetwork/phala-pherry:latest`
> `sudo phala start`

这个命令提示更新不了

**Comment by tie1234** [comment]
工人
0x9a6b5e417e6badb556f63d88b6760dead4ad7581ec309a033d2ead8922fbc227
费用账号
45mt2sivVN6FoQJL2zrbbv3cNrQn1Z1rKGEEtTxJPH2R7Moc

**Comment by tie1234** [comment]
工人
0x10deda0993413477444f7819e4e16b1ca652c4c0dd34d72438b7f2ebc5d4780c
费用账号
44UD32KL11sEyHdJehMhMi6sNxwHjHopavqbiMbY5KXv3Drx

**Comment by tie1234** [comment]
救命，12个小时没有收益 矿池显示工人状态正常 没惩罚扣v值 等回复
worker
0x7abc726973396a4f7ed70177a345c05b41c2c58c159d070b4a75968bce00042f
fee
45NX5hucK6SLMyWrBWbDaHPiZ4jUN5uDT7jFL38aMa6H8sat

**Comment by 1kuhe7pp** [comment]
worker:
0xc2d6548e9ce610b455a048efc449f6a15645a9fe48b32cfa41dce2dadeeae00a

fee:
45juFn7kzMV9qpdyiSGcAcEMaAQ3NBLSDMNs79Q6tRuVhSPi

**Comment by SuericZhe** [comment]
矿池地址:42wEDkYgZZRkApDdGa8zQfBGG7qX6eLEvdwr4w9WZjmZ26CF
工人地址: 0xe4e88c6ede60d91df78aa7c0bc982b6440520d492cbc3f82a5f817d3a463762c
gas地址: 45Hr23fup2YfWwfvLy5RfQiJvVvUKRhbCJgezYsRWZ6UKhvU
自开始mining，一直持续，都没有收益。

**Comment by tt-nb** [comment]
worker: 0xb6e6ed1c681e45471599c37bc9cb7cc5aa1d5e6d1a70fbe5c884ea95923d6655
fee account: 44wBCzj1mQaqGBX4muNCpwWJpRhPq3P4XDungjYWFR538NyD
subscan交易日志间隔12个小时才上报一次，pherry和pruntime容器都正常，请帮忙看下什么原因

**Comment by l00k** [comment]
worker: 0x1c2931fb27f2c5049604c6bb25ff63602bed0e5beb84177bfdc9a2387792000d

**Comment by h4x3rotab** [comment]
> worker: 0x1c2931fb27f2c5049604c6bb25ff63602bed0e5beb84177bfdc9a2387792000d

Could you add more context? After some investigation, I didn't find any evidence the reward is incorrect. Sometimes a newly joined worker may need to wait a few hours to get its first heartbeat request, and then it can show "pInstant" and get the first payout. However till last week, all the samples we checked are all good. (Haven't checked yours yet)

**Comment by l00k** [comment]
@h4x3rotab that was base on values fetched for that worker in 24h interval
Worker didn't went unresponsive it that period of time but rewards was at 4% APR. So I thought something could be related to this issue.
`phalaMining.miners.stats.totalReward`
