### ISSUE TITLE
pRuntime out-of-memory when syncing relay chain header

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#504]
Got reports showing that pruntime got OOM when syncing the relay chain headers. Usually they got stuck after Kusama block height ~900M.

In the past when we launch GK, we also got OOM when syncing Kusama block headers. However after reducing the batch size from 1000 to 512 the problem was bypassed. Now things get worse because multiple miners reported if they stopped mining, a new sync never succeeds.
### Solution

We already have the PR #494 merged. It increases the enclave heap allocation to 1G, and should be sufficient for most of the cases. The suggested plan for test and release is:

1. [x] Build the new pRuntime in HW mode but don't make it a release
2. [x] Run a full sync of the Khala & Kusama chain on local test environment, but skip any on-chain interaction (it will fail if we do)
3. [x] When we are confident with the regression test, we can publish it via a Council Motion, by adding the pruntime whitelist

**Comment by LeeMaster** [comment]
I think we need a checkpoint pattern . else when restart the phala we have to sync from head to current tail

**Comment by h4x3rotab** [comment]
> I think we need a checkpoint pattern . else when restart the phala we have to sync from head to current tail

That's exact our next priority

**Comment by yayoi-k** [comment]
I can confirm any miner that stops will get this error when resuming mining.  I have the issue on three miners that I happened to stop for various maintenance reasons which now cannot resume mining.

[INFO  phactory::prpc_service] Dispatching request: PhactoryAPI.SyncHeader
memory allocation of 40916286 bytes failed
./start_pruntime.sh: line 35:    24 Illegal instruction     (core dumped) STATE_FILE_PATH="$STATE_FILE_PATH" ./app $EXTRA_OPTS

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/2354113/135370635-e76389a1-9ead-42cb-9e57-9d19b465a5aa.png">

**Comment by h4x3rotab** [comment]
Fixed by #494.

@yayoi-k Thanks for the information. Indeed EPC is just a page cache instead of the full memory. There are config items that are considered in pruntime's build phase specifies the allowed memory size. It turned out we allocated too few heap but too much stack size. So in the latest pruntime release it's already fixed.
