### ISSUE TITLE
Error: Service(Client(Backend("Invalid argument: Column families not opened: col11, col10, col9, col8, col7, col6, col5, col4, col3, col2, col1, col0")))

### ISSUE THREAD

**Issue by ShilohMy** [Phala-Network/phala-blockchain#534]
Error: Service(Client(Backend("Invalid argument: Column families not opened: col11, col10, col9, col8, col7, col6, col5, col4, col3, col2, col1, col0")))
Starting Khala node as role 'MINER' with extra parachain args '--state-cache-size 671088640 --db-cache 2048 --max-runtime-instances 16' extra relaychain args '--state-cache-size 671088640 --db-cache 2048 --max-runtime-instances 16'

**Comment by jasl** [comment]
Khala database broken, you have to wipe-out them to re-sync
