### ISSUE TITLE
I cannot reclaim PHA after deleting the worker.

### ISSUE THREAD

**Issue by dy1006** [Phala-Network/phala-blockchain#552]
Delete the worker and then add the worker again. I can't reclaim PHA. Can you help me find my PHA?

pid: 3
pool owner: https://khala.subscan.io/account/42apvwUV4RLsKVxAKP24gGA7zMMc1hZz2nsD3pfpgqvmnDAu
mining status:
![image](https://user-images.githubusercontent.com/34502305/139776943-46535c8c-0408-4fc0-9c28-fbf4438d3b21.png)
code: 
https://github.com/Phala-Network/phala-blockchain/blob/1445246454fbfb635ccd7aed3a937d9d731b0760/pallets/phala/src/mining.rs#L610-L623
https://github.com/Phala-Network/phala-blockchain/blob/1445246454fbfb635ccd7aed3a937d9d731b0760/pallets/phala/src/mining.rs#L598-L604

**Comment by h4x3rotab** [comment]
Probably you are the victim of #500?

**Comment by dy1006** [comment]
> Probably you are the victim of #500?

I think so.

I found my WorkerPublicKey(0x12013ba14ff037e543377e115e77152fdea9740874279057129abe62c2e79b29) in this [list](https://github.com/Phala-Network/phala-blockchain/issues/500#issuecomment-947898462).

**Comment by h4x3rotab** [comment]
Yes, then please continue the conversation in #500. I'm closing this issue.
