### ISSUE TITLE
Releasing Stake More than 14 days

### ISSUE THREAD

**Issue by forcomwork** [Phala-Network/phala-blockchain#559]
I deleted a worker in "CoolingDown" State, but the "Releasing Stake" has not been released for more than 14 days. What should I do?
![image](https://user-images.githubusercontent.com/93892634/140673111-a3092181-b8c5-4f6f-91ee-7256d9d0ffe2.png)

**Comment by h4x3rotab** [comment]
Here's a good read: https://forum.phala.network/t/topic/3073

**Comment by forcomwork** [comment]
PhalaStakePool.reclaimPoolWorker(pid, workerPubkey) operation successfully released the amount in "releasing take"，think you very much @h4x3rotab

**Comment by h4x3rotab** [comment]
Nice
