### ISSUE TITLE
`pha_getStorageChanges` RPC should return SCALE-encoded `Vec<StorageChanges>` instead of JSON-encoded ones

### ISSUE THREAD

**Issue by krhougs** [Phala-Network/phala-blockchain#567]
Reasons:

### Performance issue

As the community keeping reporting synching from Khala being slow with `prb`, we found that this RPC method being returning huge JSON-encoded data where the block contains huge amount of events. It causes a performance issue while the returning data is processed with `JSON.parse` first, then decoded as HEX-encoded SCALE.

### Encoding behavior on Polkadot.js

Since Polkadot.js changed its behavior on encoding `Option<Vec<T>>`(https://github.com/polkadot-js/api/issues/4208), storage changes collected with `prb` is broken on some blocks(https://github.com/Phala-Network/runtime-bridge/issues/72).

**Comment by h4x3rotab** [comment]
Can add a new param to `pha_getStorageChanges` to switch between the old behavior and the new behavior (a scale data blob)
