### ISSUE TITLE
llvm 11 is installed still cargo build throws error

### ISSUE THREAD

**Issue by Harman-singh-waraich** [Phala-Network/phala-blockchain#59]
Compiling ring v0.16.9 (C:\Users\hp\desktop\phala-blockchain\ring)
  error: failed to run custom build command for `ring v0.16.9 (C:\Users\hp\desktop\phala-blockchain\ring)`

  thread 'main' panicked at 'One of the compatible llvm toolchain must exist: llvm-{11,10,9}', C:\Users\hp\desktop\phala-blockchain\ring\build.rs:376:9

**Comment by jasl** [comment]
We'll check `clang` and `llvm-ar` commands are accessible from `PATH`, if not, it will give the error

**Comment by Harman-singh-waraich** [comment]
both are accessible

**Comment by jasl** [comment]
Ok I got it, it seems we don't handle `llvm-ar` <https://github.com/Phala-Network/phala-blockchain/blob/master/ring/build.rs#L362>

I pushed a dirty patch to fix this.

PS: I'm not sure we (and Substrate/Polkadot) support Windows...

**Comment by Harman-singh-waraich** [comment]
Ring error didn't come but this happened.

 Compiling phala-node-runtime-wasm v1.0.0 (C:\Users\hp\desktop\phala-blockchain\target\release\wbuild\phala-node-runtime)
  error: linking with `rust-lld` failed: exit code: 1
    |
    = note: "rust-lld" "-flavor" "wasm" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--fatal-warnings" "--no-demangle" "--export-dynamic" "--no-entry" "-L" "C:\\Users\\hp\\.rustup\\toolchains\\nightly-2020-08-23-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-unknown\\lib" "-L" "C:\\Users\\hp\\.rustup\\toolchains\\nightly-2020-08-23-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-unknown\\lib\\self-contained" "C:\\Users\\hp\\desktop\\phala-blockchain\\target\\release\\wbuild\\target\\wasm32-unknown-unknown\\release\\deps\\phala_node_runtime.phala_node_runtime.6d8qokol-cgu.0.rcgu.o" "-o" "C:\\Users\\hp\\desktop\\phala-blockchain\\target\\release\\wbuild\\target\\wasm32-unknown-unknown\\release\\deps\\phala_node_runtime.wasm" "--export" "AccountNonceApi_account_nonce" "--export" "AuthorityDiscoveryApi_authorities" "--export" "BabeApi_configuration" "--export" "BabeApi_current_epoch_start" "--export" "BabeApi_generate_key_ownership_proof" "--export" "BabeApi_submit_report_equivocation_unsigned_extrinsic" "--export" "BlockBuilder_apply_extrinsic" "--export" "BlockBuilder_check_inherents" "--export" "BlockBuilder_finalize_block" "--export" "BlockBuilder_inherent_extrinsics" "--export" "BlockBuilder_random_seed" "--export" "ContractsApi_call" "--export" "ContractsApi_get_storage" "--export" "ContractsApi_rent_projection" "--export" "Core_execute_block" "--export" "Core_initialize_block" "--export" "Core_version" "--export" "GrandpaApi_generate_key_ownership_proof" "--export" "GrandpaApi_grandpa_authorities" "--export" "GrandpaApi_submit_report_equivocation_unsigned_extrinsic" "--export" "Metadata_metadata" "--export" "OffchainWorkerApi_offchain_worker" "--export" "SessionKeys_decode_session_keys" "--export" "SessionKeys_generate_session_keys" "--export" "TaggedTransactionQueue_validate_transaction" "--export" "TransactionPaymentApi_query_info" "--export=__heap_base" "--export=__data_end" "--gc-sections" "--no-entry" "-O3" "-L" "C:\\Users\\hp\\desktop\\phala-blockchain\\target\\release\\wbuild\\target\\wasm32-unknown-unknown\\release\\deps" "-L" "C:\\Users\\hp\\desktop\\phala-blockchain\\target\\release\\wbuild\\target\\release\\deps" "-L" "C:\\Users\\hp\\desktop\\phala-blockchain\\target\\release\\wbuild\\target\\wasm32-unknown-unknown\\release\\build\\ring-f11a2ec710ffe892\\out" "-L" "C:\\Users\\hp\\.rustup\\toolchains\\nightly-2020-08-23-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-unknown\\lib" "C:\\Users\\hp\\AppData\\Local\\Temp\\rustcmXSgkW\\libring-19eb8569dd93c285.rlib" "C:\\Users\\hp\\.rustup\\toolchains\\nightly-2020-08-23-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-unknown\\lib\\libcompiler_builtins-b3896b8b17801e7d.rlib" "--export-table" "--export=__heap_base" "--import-memory"
    = note: rust-lld: error: Invalid record
            rust-lld: error: Invalid record
            rust-lld: error: Invalid record
            rust-lld: error: Invalid record
            rust-lld: error: Invalid record


  error: aborting due to previous error

  error: could not compile `phala-node-runtime-wasm`.

  To learn more, run the command again with --verbose.
  error: process didn't exit successfully: `C:\Users\hp\desktop\phala-blockchain\target\release\wbuild-runner\phala-node-runtime17888466565001065857\target\x86_64-pc-windows-msvc\release\wasm-build-runner-impl.exe` (exit code: 1)

PS: i think substrate supports windows. they have pre-requisites for installation of substrate on windows.

**Comment by jasl** [comment]
Sorry, we are not tested on Windows yet, so I can't figure out this problem now, could you try WSL or Ubuntu?

Polkadot suggest to use WSL on windows <https://wiki.polkadot.network/docs/en/maintain-sync#fast-install-instructions-windows>.

**Comment by h4x3rotab** [comment]
So far we haven't tested if the blockchain can build on Windows. Apparently Substrate recently added a tutorial to build it on Windows. In theory our blockchain should work in the same way as Substrate.

However, we have "ring-wasm" in addition in our blockchain runtime. When we write the environment detection code in "ring-wasm", we hadn't kept Windows compatibility in our mind. I guess this is the cause of the problem.

Though we can fix this, our pRuntime is still Linux only. It relies on teaclave-sgx-sdk, a Linux only SDK. So if you want to run the full stack, a real Linux is still required. Virtual machine should work. Not sure if WSL works.

**Comment by h4x3rotab** [comment]
Created the tracking issue: #61

**Comment by Harman-singh-waraich** [comment]
I migrated to ubuntu vm. It works there
