### ISSUE TITLE
[fat contract] Key assignment for contract-created contracts

### ISSUE THREAD

**Issue by kvinwang** [Phala-Network/phala-blockchain#606]
Currently, workers always report the infomation of new created contracts to the chain.

**Comment by shelvenzhou** [comment]
The key is generated at the cluster level, which means there is no need to generate a new key for contract-created contracts.

**Comment by shelvenzhou** [comment]
This is further optimized in #663, now the `ClusterKey` is distributed to deployed workers, so they can derive the `ContractKey` totally off-chain if any contract is created.
