### ISSUE TITLE
Check LLVM version

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#61]
Currently we depends on the filename in $PATH to determine the version of llvm (`clang-${ver}` and `llvm-ar-${ver}`). It doesn't work for the system built-in installations like the ones coming from Xcode, or Windows installation.

A better way could be to check `llvm-config --version` according to [this answer](https://stackoverflow.com/questions/38927132/how-to-determine-the-llvm-version).

**Comment by flipchan** [comment]
@h4x3rotab is this issue still active?

**Comment by h4x3rotab** [comment]
I believe so. Currently we just assume the LLVM and CLANG in $PATH is the desired version. The build script cannot tell if it's too old.

**Comment by h4x3rotab** [comment]
@flipchan We'd love to give a small bounty if you can take this task

**Comment by flipchan** [comment]
@h4x3rotab sure thing! I will look into it

**Comment by flipchan** [comment]
@h4x3rotab can you give me some kind of write privledge? I can not create new branches, so cant push my pr
```shell
git push -u origin llvm_sync
ERROR: Permission to Phala-Network/phala-blockchain.git denied to flipchan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


```

**Comment by flipchan** [comment]
@h4x3rotab  pr: https://github.com/Phala-Network/phala-blockchain/pull/619

**Comment by h4x3rotab** [comment]
Closed since nobody is following and nobody is reporting the problem.
