### ISSUE TITLE
Expose ink! events

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#737]
Event (log) is a basic feature of smart contracts and it's also supported by ink!. This will be important for developers to build services that consumes the output from the contract. We should consider:

1. Should Fat Contract support event export?
2. If yes, should the exported events be permissionless (in plain text and accessible by everyone) or permissioned?
3. How do we export the events and how long to keep in pruntime?

**Comment by h4x3rotab** [comment]
Note that currently all the communication from ink! to sidevm is through the event. If we publish the events, the communication will be published

**Comment by kvinwang** [comment]
> 3\. How do we export the events and how long to keep in pruntime?

It might not a good idea to cache logs/event inside pruntime. The memory of pruntime is expensive.
If it's for debug only, consider emit the logs out via UDP in realtime and collect it with a log server.

**Comment by h4x3rotab** [comment]
For the resource concerns, we can save the logs in a file or the kvdb and write it to the disk. I think saving some recent logs is necessary because even if we introduce some external log storage (i.e. log server), we still want to make sure the log can be correctly persisted without missing entries.

**Comment by kvinwang** [comment]
So what? All of these can be done externally, easier and better. Do we really want to make the pruntime more and more complicate by building in these features should not be necessary to be built-in?

**Comment by h4x3rotab** [comment]
I agree with the idea to minimize pruntime. For this specific problem, I tried to not assume any implementation detail as much as possible. But in my understanding if we want to reliable persist the events somewhere outside pruntime, we must make sure the emitted event is committed before dropping the event. Take a remove log server as an example, the server may crash, and the internet may break up. In such case, if we take no measure, the integrity of the event stream cannot be guaranteed.

**Comment by h4x3rotab** [comment]
Closed via #855
