### ISSUE TITLE
pruntime checkpoint.seal corruption when rebooting or restarting LFM

### ISSUE THREAD

**Issue by Nexus2k** [Phala-Network/phala-blockchain#752]
I use the latest prb setup (see https://github.com/Nexus2k/khala-ansible) and whenever I reboot the machine or restart LFM while it's sending blocks to the miners it seems to corrupt their state.
LFM then complains after the next reboot with the following message:
`"msg":"Worker stopped due to error: TypeError: Cannot read properties of undefined (reading 'parentProcessedHeight')\n    at headerSyncIterator (/opt/app/dist/lifecycle/runner/sync.js:78:29)\n    at [headerSyncIterator.next](http://headersynciterator.next/) (<anonymous>)\n    at iterate (/opt/app/dist/lifecycle/runner/sync.js:168:22)\n    at startSync (/opt/app/dist/lifecycle/runner/sync.js:119:29)\n    at onSynching (/opt/app/dist/lifecycle/runner/state_machine.js:58:51)\n    at /opt/app/dist/lifecycle/runner/state_machine.js:30:66\n    at /opt/app/node_modules/finity/lib/utils/invokeEach.js:11:15\n    at Array.forEach (<anonymous>)\n    at invokeEach (/opt/app/node_modules/finity/lib/utils/invokeEach.js:10:7)\n    at StateMachine.executeTransition (/opt/app/node_modules/finity/lib/core/StateMachine.js:113:30)"`

However when I call /get_info endpoint on the worker directly it correctly shows the last block state:
`{"payload":"{\"blocknum\":20961,\"dev_mode\":false,\"ecdh_public_key\":\"xxx\",\"gatekeeper\":{\"master_public_key\":\"\",\"role\":0},\"genesis_block_hash\":\"ff93a4a903207ad45af110a3e15f8b66c903a0045f886c528c23fe7064532b08\",\"git_revision\":\"626694880e02255cc546395e386f5fd3e7c4b21f\",\"headernum\":9473381,\"initialized\":true,\"machine_id\":\"xxx\",\"memory_usage\":{\"rust_peak_used\":19102364,\"rust_used\":17749617,\"total_peak_used\":58814464},\"para_headernum\":493872,\"pending_messages\":0,\"public_key\":\"xxx\",\"registered\":false,\"running_side_tasks\":0,\"score\":0,\"state_root\":\"94f71ecdb5332b5007469eceae8c5cf678f63247ed734e810106cd49dfc10ea1\",\"version\":\"0.2.2\"}","signature":"62ee4acdc5345c8834301195a79e82667de35e439584c46179e62d0c3c12007cbe3c4e403562e9789c1ff5df04b19baecb4ce3ef7fdde8caa6851baa8dcdd784","status":"ok"}`

The processing of these blocks is really really slow and it would be great if there is a way that the miner doesn't have to process the whole chain after removing the *.seal files.

**Comment by Nexus2k** [comment]
I believe the LFM might not be able to shutdown within the default 10 seconds container stop timeout. So increasing that timeout to something like 60 seconds might help with the corruption.

**Comment by Nexus2k** [comment]
I've now rebooted the LFM container several times but with `-t 60` and the workers didn't corrupt anymore. Is it generally recommended to restart the LFM by restarting the phala-node or rather by restarting the container directly?

**Comment by h4x3rotab** [comment]
Hello. It looks like a problem in PRB, not in the pruntime side. It's better to create an issue in runtime-bridge repo.

> The processing of these blocks is really really slow and it would be great if there is a way that the miner doesn't have to process the whole chain after removing the *.seal files.

Yes, we are aware of that. So far the syncing states are stored in the seal files, which is associated with the pruntime identity key pair. When it's deleted, pruntime must sync from scratch. To implement the security model properly, it may not be easy to detach the syncing states from the pruntime identity. However, the current work on persist kvdb may help it in the long term. Once the basic problems are resolved, we can try to optimize the historical data syncing process.

**Comment by Nexus2k** [comment]
Never the less I need a way to successfully recover from that state. Any ideas? Does pruntime need to be stopped as the first component in the stack and then the others or where can I find the interaction and start/stop routines?

**Comment by Nexus2k** [comment]
OMG this is so annoying, looks like if the lifecycle component is restarted w/o stopping all workers first, **one CAN recover from the state when restarting the miner process from the Monitor UI**. If I knew this before I could have saved 3 days of unresponsive miner...

**Comment by Nexus2k** [comment]
But ultimately I agree this is the runtime-bridge that is at fault. I might have misunderstood the "monorepo" concept you mention somewhere in the docs.
