### ISSUE TITLE
pha_getStorageChangesAt on Phala

### ISSUE THREAD

**Issue by ngrewe** [Phala-Network/phala-blockchain#799]
Hi all,

I'm observing a discrepancy between the behaviour of khala-node v0.1.13 on the Khala and Phala chains. On Khala, the `pha_getStorageChangesAt` RPC call works fine:

```
$ curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d   '{
      "jsonrpc":"2.0",
       "id":1,
       "method":"pha_getStorageChangesAt",
       "params": ["0xeb430cded807070b2df8543762ebd38fdd4f87d0798c2a43392e36bd0a3c5f4f"]
     }'
{"jsonrpc":"2.0","result":"0x7903…⟨more block data⟩…", ,"id":1}
```

But on a node connected to the Phala chain, it get a method not found result:
```
$ curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d   '{
      "jsonrpc":"2.0",
       "id":1,
       "method":"pha_getStorageChangesAt",
       "params": ["0x5d96107df35d5418b3c1ed5d0a591fb173fc96ca3ea1541c047d86d975fa2488"]
     }'
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

This prevents the PRB data_provider from successfully connecting to a Phala node.

**Comment by jasl** [comment]
> Hi all,
> 
> I'm observing a discrepancy between the behaviour of khala-node v0.1.13 on the Khala and Phala chains. On Khala, the `pha_getStorageChangesAt` RPC call works fine:
> 
> ```
> $ curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d   '{
>       "jsonrpc":"2.0",
>        "id":1,
>        "method":"pha_getStorageChangesAt",
>        "params": ["0xeb430cded807070b2df8543762ebd38fdd4f87d0798c2a43392e36bd0a3c5f4f"]
>      }'
> {"jsonrpc":"2.0","result":"0x7903…⟨more block data⟩…", ,"id":1}
> ```
> 
> But on a node connected to the Phala chain, it get a method not found result:
> 
> ```
> $ curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d   '{
>       "jsonrpc":"2.0",
>        "id":1,
>        "method":"pha_getStorageChangesAt",
>        "params": ["0x5d96107df35d5418b3c1ed5d0a591fb173fc96ca3ea1541c047d86d975fa2488"]
>      }'
> {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
> ```
> 
> This prevents the PRB data_provider from successfully connecting to a Phala node.

Phala parachain not integrate mining system yet so you can't use this RPC yet
