### ISSUE TITLE
On-chain runtime upgrade breaks subxt signature

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#91]
Transaction signature commits to the runtime spec version. When we get an on-chain runtime upgrade, the spec version increases. However if phost is in a long run, it doesn't detect it automatically. As a result, once the upgrade happens, subxt starts to produce invalid transactions with the wrong signature:

> 1010: Invalid Transaction: Transaction has a bad signature

Related:

- https://github.com/paritytech/txwrapper/issues/66

**Comment by zaketac** [comment]
+1

**Comment by h4x3rotab** [comment]
This also apply to polkadot.js

**Comment by h4x3rotab** [comment]
Fixed by #545
