### ISSUE TITLE
[help] Does it worker node  support on WSL2

### ISSUE THREAD

**Issue by AlexiaChen** [Phala-Network/phala-blockchain#960]
I found it worker nodes and gatekeepers all need Intel SGX tech to run **pRuntime**（enclave）. so if I run it on WSL2, the dev/test environment of the whole blockchain cannot correctly setup on my local  computer? right?

CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz  
cannot find it Intel official website https://www.intel.com/content/www/us/en/support/articles/000028173/processors.html

so, my local host machine's CPU does not support Intel SGX and it definitely cannot setup local dev/test phala network, right?

**Comment by h4x3rotab** [comment]
Yes, you can run it in simulation mode. SGX simulation mode doesn't require any special hardware. Any Linux environment should work.

To set up a local testnet, check the [instructions](https://github.com/Phala-Network/phala-blockchain/tree/master/scripts/run)

**Comment by AlexiaChen** [comment]
> Yes, you can run it in simulation mode. SGX simulation mode doesn't require any special hardware. Any Linux environment should work.
> 
> To set up a local testnet, check the [instructions](https://github.com/Phala-Network/phala-blockchain/tree/master/scripts/run)

Thanks!
