### ISSUE TITLE
HelloWorld branch: Build failing due to braces on panic! in ring/build.rs (line 376)

### ISSUE THREAD

**Issue by ctnimmo** [Phala-Network/phala-blockchain#98]
As per title: Line 376 of ring/build.rs has braces in the panic message causing cargo build --release to fail

**Comment by ctnimmo** [comment]
This is for the tutorial build (helloWorld branch)

**Comment by h4x3rotab** [comment]
@ctnimmo Thanks for reporting. However could you check if you have llvm >=9 installed? The build script should only complain when it fails to find the correct version of `clang` and `ar`.

**Comment by ctnimmo** [comment]
Using a fresh build - so, I don't have clang, so I will install it

BUT before I do ...

the error is a real one occurring on the with the error msg itself (braces on the error message have no reference).

As the error is on the error/panic message this is perhaps more of a "niggle".

Before installing clang I'll see if I can hit/repair any of these more of these "niggles" - will just help with a smoother newcomer experience (plus I'll request an update to tutorial to include clang install).

FYI my setup is:

Dell Latitude 5490
Intel CORE i5, vPro, 8th Gen (i.e. Intel® Core™ i5-8350U CPU @ 1.70GHz × 8)
Ubuntu 20.04.1 LTS
rustup 1.23.1
rustc 1.48.0
cargo 1.48.0
LLVM version 10.0.0
node v15.3.0
yarn 2.4.0 (was yarn 1.22.10 but ran: **yarn set version berry** to bring it up to v2, which should be added to the tutorial, although I doubt yarn v1 would affect build).

**Comment by ctnimmo** [comment]
Isolated the issue - the latest Rust compiler does not work with the helloworld branch.

Rather than alter the code I've decided that an update to the wiki/docs would be better in this case.

I've added an issue and PR for the wiki. I think a stable tutorial would be better (in my opinion) than one that needs to keep up with the latest changes - potentially introduces bugs with each change. New users just want to get a feel for how things work - they can worry about how to keep code up to date at a later stage.

Issue: **Tutorial does not compile**
https://github.com/Phala-Network/phala-wiki/issues/23

PR: **Amendments to dev tutorial including targeting Rust nightly-2020-10-01**
https://github.com/Phala-Network/phala-wiki/pull/22

**Comment by ctnimmo** [comment]
@h4x3rotab if my comments make sense, please feel free to close this issue. (Also please check out the wiki repo, as per my comments above).

**Comment by h4x3rotab** [comment]
We should change this line:

https://github.com/Phala-Network/phala-blockchain/blob/77e9e7a8477c530495df46e877dec6a2e75c89bf/ring/build.rs#L390

In `panic!` macro, "{9,10,11}" is not good in the format pattern. We should write something like:

```rust
panic!("{}", "One of the compatible llvm toolchain must exist: llvm-{11,10,9}");
```
