### ISSUE TITLE
failed to run custom build command for `phala-node-runtime v2.0.0`

### ISSUE THREAD

**Issue by pencoa** [Phala-Network/phala-blockchain#992]
Error in `cargo build --release`
```
error: failed to run custom build command for `phala-node-runtime v2.0.0 (/Users/xxx/Code/phala-blockchain/standalone/runtime)`

Caused by:
  process didn't exit successfully: `/Users/xxx/Code/phala-blockchain/target/release/build/phala-node-runtime-bd2d74b89878e0da/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/Users/xxx/.rustup/toolchains/nightly-2022-09-08-aarch64-apple-darwin/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/xxx/Code/phala-blockchain/target/release/wbuild/phala-node-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.65.0-nightly (c2804e6ec 2022-09-07)


  --- stderr
  warning: Patch `rocket v0.5.0-rc.2 (https://github.com/SergioBenitez/Rocket#6c3d35e7)` was not used in the crate graph.
  Check that the patched package version and available features are compatible
  with the dependency requirements. If the patch has a different version from
  what is locked in the Cargo.lock file, run `cargo update` to use the new
  version. This may also occur with an optional dependency that is not enabled.
```

**Comment by jasl** [comment]
Which rustc you're using? and which OS?

**Comment by pencoa** [comment]
## System information
```
macOS Monterey
version 12.6(21G115)
chip Apple M2
```
## Dependencies

### LLVM
```
llvm-config --version
15.0.0
```

### Rust
```
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
info: checking for self-updates

   stable-aarch64-apple-darwin unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
  nightly-aarch64-apple-darwin unchanged - rustc 1.66.0-nightly (db0597f56 2022-10-11)

info: cleaning up downloads & tmp directories
```

**Comment by jasl** [comment]
> ## System information
> ```
> macOS Monterey
> version 12.6(21G115)
> chip Apple M2
> ```
> 
> ## Dependencies
> ### LLVM
> ```
> llvm-config --version
> 15.0.0
> ```
> 
> ### Rust
> ```
> info: syncing channel updates for 'stable-aarch64-apple-darwin'
> info: syncing channel updates for 'nightly-aarch64-apple-darwin'
> info: checking for self-updates
> 
>    stable-aarch64-apple-darwin unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
>   nightly-aarch64-apple-darwin unchanged - rustc 1.66.0-nightly (db0597f56 2022-10-11)
> 
> info: cleaning up downloads & tmp directories
> ```

For macOS can you confirm you're using custom installed LLVM not Xcode bundled? see https://github.com/Phala-Network/khala-parachain#special-note-for-macos

**Comment by pencoa** [comment]
> > ## System information
> > ```
> > macOS Monterey
> > version 12.6(21G115)
> > chip Apple M2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Dependencies
> > ### LLVM
> > ```
> > llvm-config --version
> > 15.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Rust
> > ```
> > info: syncing channel updates for 'stable-aarch64-apple-darwin'
> > info: syncing channel updates for 'nightly-aarch64-apple-darwin'
> > info: checking for self-updates
> > 
> >    stable-aarch64-apple-darwin unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
> >   nightly-aarch64-apple-darwin unchanged - rustc 1.66.0-nightly (db0597f56 2022-10-11)
> > 
> > info: cleaning up downloads & tmp directories
> > ```
> 
> For macOS can you confirm you're using custom installed LLVM not Xcode bundled? see https://github.com/Phala-Network/khala-parachain#special-note-for-macos

It works. My LLVM has upgraded and I doesn't set link again.

But there is another compile error
```
error: expected identifier or literal
  --> crates/phactory/api/src/storage_sync.rs:24:49
   |
24 |     #[display(fmt = "HeaderValidateFailed({})", .0)]
   |                                                 ^

error: could not compile `phactory-api` due to previous error
```
It seems that this syntax is compatible to [displaythis crate](https://docs.rs/displaythis/latest/displaythis/).
Maybe some display macro dependency had changed. 
I replace 
```
pub enum Error {
    /// Header validation failed
    #[display(fmt = "HeaderValidateFailed({})", .0)]
    HeaderValidateFailed(String),
    /// Storage proof failed
    #[display(fmt = "StorageProofFailed({})", .0)]
    StorageProofFailed(String),
}
```
to 
```
pub enum Error {
    /// Header validation failed
    #[display(fmt = "HeaderValidateFailed({})", self)]
    HeaderValidateFailed(String),
    /// Storage proof failed
    #[display(fmt = "StorageProofFailed({})", self)]
    StorageProofFailed(String),
}
```

The error solved. 
If I could make a pull request to solve this error?

**Comment by jasl** [comment]
> > > ## System information
> > > ```
> > > macOS Monterey
> > > version 12.6(21G115)
> > > chip Apple M2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ## Dependencies
> > > ### LLVM
> > > ```
> > > llvm-config --version
> > > 15.0.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Rust
> > > ```
> > > info: syncing channel updates for 'stable-aarch64-apple-darwin'
> > > info: syncing channel updates for 'nightly-aarch64-apple-darwin'
> > > info: checking for self-updates
> > > 
> > >    stable-aarch64-apple-darwin unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
> > >   nightly-aarch64-apple-darwin unchanged - rustc 1.66.0-nightly (db0597f56 2022-10-11)
> > > 
> > > info: cleaning up downloads & tmp directories
> > > ```
> > 
> > 
> > For macOS can you confirm you're using custom installed LLVM not Xcode bundled? see https://github.com/Phala-Network/khala-parachain#special-note-for-macos
> 
> It works. My LLVM has upgraded and I doesn't set link again.
> 
> But there is another compile error
> 
> ```
> error: expected identifier or literal
>   --> crates/phactory/api/src/storage_sync.rs:24:49
>    |
> 24 |     #[display(fmt = "HeaderValidateFailed({})", .0)]
>    |                                                 ^
> 
> error: could not compile `phactory-api` due to previous error
> ```
> 
> It seems that this syntax is compatible to [displaythis crate](https://docs.rs/displaythis/latest/displaythis/). Maybe some display macro dependency had changed. I replace
> 
> ```
> pub enum Error {
>     /// Header validation failed
>     #[display(fmt = "HeaderValidateFailed({})", .0)]
>     HeaderValidateFailed(String),
>     /// Storage proof failed
>     #[display(fmt = "StorageProofFailed({})", .0)]
>     StorageProofFailed(String),
> }
> ```
> 
> to
> 
> ```
> pub enum Error {
>     /// Header validation failed
>     #[display(fmt = "HeaderValidateFailed({})", self)]
>     HeaderValidateFailed(String),
>     /// Storage proof failed
>     #[display(fmt = "StorageProofFailed({})", self)]
>     StorageProofFailed(String),
> }
> ```
> 
> The error solved. If I could make a pull request to solve this error?

Sure, thank you!

**Comment by jasl** [comment]
Since the compiling error solved, I'm closing this issue, feel free to reopen it.
